/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home.route'
import { Route as AboutRouteImport } from './routes/about.route'

// Create/Update Routes

const HomeRouteRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const AboutRouteRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/about': typeof AboutRouteRoute
  '/home': typeof HomeRouteRoute
}

export interface FileRoutesByTo {
  '/about': typeof AboutRouteRoute
  '/home': typeof HomeRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/about': typeof AboutRouteRoute
  '/home': typeof HomeRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/home'
  id: '__root__' | '/about' | '/home'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AboutRouteRoute: typeof AboutRouteRoute
  HomeRouteRoute: typeof HomeRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  AboutRouteRoute: AboutRouteRoute,
  HomeRouteRoute: HomeRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/about",
        "/home"
      ]
    },
    "/about": {
      "filePath": "about.route.tsx"
    },
    "/home": {
      "filePath": "home.route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
